### PR TITLE
Added configuration to redirect to cart or on a separate fail page on…

### PR DESCRIPTION
**Pull request by BushraAsif**
… error

### CODE REVIEW

**Comment by maf-embraceit** [comment]
All changes have been reviewed.

**Comment by emicha** [comment]
An system error between the Merchant and Gateway should not be displayed to the customer, but logged in the application log:
image

**Comment by BushraAsif** [comment]
> An system error between the Merchant and Gateway should not be displayed to the customer, but logged in the application log: 

This has been updated and the error will appear when the gateway configuration is enabled for it. Meaning that when the "cardHolderErrorMessageMustBeShown" is true then it will show the gateway error otherwise it will show "Internal Error". Also, we are maintaining the gateway error in the application log file.

**Comment by emicha** [comment]
image
- errorMessage: Error to be shown to the user
- merchantErrorMessage: System error for the merchant’s record
- cardHolderErrorMessage: Specific message that must be shown in case cardHolderErrrorMessageMustBeShown = true

We should not show merchantErrorMessage to the customer.

**Comment by BushraAsif** [comment]
> image
> 
> * errorMessage: Error to be shown to the user
> * merchantErrorMessage: System error for the merchant’s record
> * cardHolderErrorMessage: Specific message that must be shown in case cardHolderErrrorMessageMustBeShown = true
> 
> We should not show merchantErrorMessage to the customer. Am I correct to interpret that this is what we are showing to the customer? In that case, we should remove that block.

No, We are just saving merchant error in the log. It will not be shown to the customer

**Review by emicha — APPROVED** [review]

**Pull request merged**
